### ISSUE TITLE
Meta: documentation

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/neon#692]
We have a lot to document; some ideas are:

- [x] getting started guide to neon #1089 
- [x] document our public api (the linting rules package_api_docs and package_api_docs can help here) #1089
- [x] document internal processes lke #575 
- [x] make current docs more prominent in the readme
<s>- [ ] document adding new platforms</s>
- [x] document adding a new app
- [x] document usage of a rebase workflow (contributing.md)
- [x] replace readme desctiprion with the three goals of neon
- [x] add slides after the lightning talk
- [x] add link to recording of the talk
- [x] document nextcloud dev server dying
- [x] document how to use dynamite #1088 
- [x] document how to use nextcloud package #1087 
- [x] document needed dev packages (ayatana, sqlite, yq)
- [x] document the need of signing commits
- [ ] document nextcloud server in architecture overview to avoid confusion with the nextcloud package
- [x] document good first issue
- [x] document the need of contributing clients back so other apps can make use of them.

**Comment by Leptopoda** [comment]
While this is not a stopper I'll add it to the 1.0 milestone as we should try to tackle as much as we can before the relase

**Comment by provokateurin** [comment]
The remaining tasks are not needed for the nextcloud package release, so it shouldn't have the milestone set?
